### ISSUE TITLE
keep the library structure

### ISSUE THREAD

**Issue by laurentperrinet** [papis/papis-zotero#11]
I managed to import my references from Zotero - but I am missing the directory structure that I have build over the years...

Any way to retrieve that information to buils my `papis` library?

(I am using the latest git code)

**Comment by alexfikl** [comment]
Unfortunately, `papis` mostly keeps a flat directory structure and allows tagging (and querying tags) to group documents together. When importing from [Zotero metadata](https://www.zotero.org/support/collections_and_tags), the tags are saved in a `tags` field and the collections in a `collections` field.

You can then query those using e.g. for the `papis` db backend
```
papis list -a 'tags:<some-tag>'
papis list -a 'collections:<some-collection>'
```
You can check out the documentation for more information: https://papis.readthedocs.io/en/latest/database_structure.html.
