### ISSUE TITLE
bibtex import with multiple attached files

### ISSUE THREAD

**Issue by jghauser** [papis/papis-zotero#15]
First of all, thank you so much for developing papis! I've been trying to ditch zotero for a while, and it now seems finally possible.

I've got an issue importing from zotero however. Importing from `zotero.sqlite` doesn't seem to work, but I've opened another issue about this. When I use bibtex import, it works but only copies a single `file` entry. Unfortunately many of my zotero entries have also attached notes and html snapshots.

Is there some way of importing all attached files? I've checked the bibtex file and references to all files are there, separated by a semicolon:

```
@article{olson_extended_2011,
	title = {The {Extended} {Self}},
	volume = {21},
	number = {4},
	journal = {Minds and Machines},
	author = {Olson, Eric T.},
	year = {2011},
	keywords = {distributed cognition, extended self, mind and cognition, philosophy, philosophy of mind, self},
	pages = {481--495},
	file = {Olson_2011_The_Extended_Self.md:/home/julian/.zotero/zotero/nd6r5fbf.default/zotero/storage/H8PMNP68/Olson_2011_The_Extended_Self.md:text/markdown;Olson_2011_The_Extended_Self.pdf:/home/julian/.zotero/zotero/nd6r5fbf.default/zotero/storage/A5SHQM4I/Olson_2011_The_Extended_Self.pdf:application/pdf;PhilPapers - Snapshot:/home/julian/.zotero/zotero/nd6r5fbf.default/zotero/storage/HW2X6TAT/undefined.html:text/html}
}
```

**Comment by alejandrogallo** [comment]
Hi! Well I see no reason why this shouldn't be implemented, but maybe we can do it in
`papis bibtex import`, maybe it's better to have a robust bibtex importer
and have it on `papis core`. I can modify the importer there so that it tries several combinations in the
`file` field and tries to get all possible attached files.

**Comment by jghauser** [comment]
Ok, that makes sense. I just tried with `papis bibtex import` and it already imports multiple files without problems! Thanks!

**Comment by alejandrogallo** [comment]
Actually I reviewed the `papis bibtex import` code and it already does this

https://github.com/papis/papis/blob/5f44a8de6d7c2044cc813f1bf26a90d381cbae7b/papis/commands/bibtex.py#L450

So this should work there

**Comment by alejandrogallo** [comment]
It seems that we wrote at the same time ;) glad it worked out!
