### ISSUE TITLE
PyPI Version 0.1.0 Broken

### ISSUE THREAD

**Issue by Fischmiep** [papis/papis-zotero#17]
Hey everyone,

I just installed `papis-zotero` via `pip` and encountered the same issue that was described in #16. It seems that `pip`, by default, installs version `0.0.3` (you should be able to reproduce this in a fresh venv). Following the advice mentioned in the issue, I tried installing version `0.1.0` by specifying the version (note that just specifying `0.1.0` as the version does not seem to be sufficient):

```
$ pip3 install papis-zotero==0.1.0

ERROR: Could not find a version that satisfies the requirement papis-zotero==0.1.0 (from versions: 0.1.0.linux-x86_64, 0.0.1, 0.0.2, 0.0.3)
ERROR: No matching distribution found for papis-zotero==0.1.0


$ pip3 install papis-zotero==0.1.0.linux-x86_64

Collecting papis-zotero==0.1.0.linux-x86_64
  Using cached papis-zotero-0.1.0.linux-x86_64.tar.gz (14 kB)
ERROR: papis-zotero==0.1.0.linux-x86_64 from https://files.pythonhosted.org/packages/2d/62/f885aa6a9e682cb53321cbaac98c3e08b9a3c30f76972bd28236e569f72e/papis-zotero-0.1.0.linux-x86_64.tar.gz does not appear to be a Python project: neither 'setup.py' nor 'pyproject.toml' found.
```

I found this weird and investigated a little further by manually downloading both package versions from PyPI and looking at the content. After extracting, package version [`0.0.3`](https://pypi.org/project/papis-zotero/0.0.3/) indeed has the expected content. However, package version [`0.1.0`](https://pypi.org/project/papis-zotero/0.1.0/) only contains what appears to be a copy of the directory structure of a package installation.

Personally, I worked around this by downloading the release from GitHub and installing it from source. However, I suggest fixing this by providing a new upstream package of the latest release.

**Comment by alejandrogallo** [comment]
This should be fixed hopefully in version 0.1.1, could you check again?

**Comment by Fischmiep** [comment]
Same issue with [`0.1.1`](https://pypi.org/project/papis-zotero/0.1.1/) on PyPI.

**Comment by alexfikl** [comment]
@alejandrogallo Can confirm! The archive at
https://pypi.org/project/papis-zotero/0.1.1/#files
has a weird structure with files in `home/gallo/software/papis/env/lib/python3.10/site-packages/`, so it looks like it was packaged incorrectly.

**Comment by alejandrogallo** [comment]
I apologize for this, I just pushed a new version 0.1.2 that should not have that problem. I hope this is fine now!!

Sorry for the delay!

**Comment by Fischmiep** [comment]
That seems to have done the trick. Thanks for the update!
