### ISSUE TITLE
papis open 

### ISSUE THREAD

**Issue by tjallemaal** [papis/papis-zotero#29]
when entering `papis open` the expected behaviour is to get a list of the whole database  entries ( as I enjoy having it on arch)
Now on MacOS I get an error stating `[WARNING] commands.list: No documents retrieved`.

my config looks like this

```
[papers]
dir = ~/Documents/mypapers

[settings]
whoosh-schema-fields = ['author', 'year', 'project', 'title']
database-backend = whoosh
default-library = papers
add-edit = True
add-confirm = True
add-folder-name = {doc[author_list][0][family]} - {doc[title]}
add-file-name = {doc[author_list][0][family]} - {doc[title]} -{doc[year]}
editor = nvim
use-cache = False


[tui]
editmode = nvim
```

not sure what I'm missing here.
BTW when specifying the command with, say , `papis open 'author:chomsky'` I actually get a nice result list.

Thanks!

**Comment by alexfikl** [comment]
Does this do what you want
```
papis open '*'
```
? If yes, it seems like there's a mismatch in the default query string and you may want to add
```
default-query-string = "*"
```
to your configuration. Otherwise, I'm not quite sure what could be wrong if specifying a query works just fine :confused:

**Comment by tjallemaal** [comment]
yes! it worked. still a long wait to go. so much to unravel. :) thanks again
