### ISSUE TITLE
~/.cache/papis is not refreshed on import

### ISSUE THREAD

**Issue by mcepl** [papis/papis-zotero#32]
This is the follow-up on #31:

> Yeah, I'm afraid the SQLite importer just writes out the info.yaml files and doesn't let papis known it needs to update the database :\

When the import from SQLite happens, the cache in `~/.cache/papis/` is not updated and `papis list` (and other commands) produces non-sensical results.

**Comment by kiike** [comment]
Since we are now importing via the papis API, #43, I believe this is already addressed.

**Comment by alexfikl** [comment]
Agreed. Feel free to re-open or open a new issue if there are still a bug here!
