### ISSUE TITLE
TODO: Get a zotero.sqlite file for testing and a bibtex dump for testing

### ISSUE THREAD

**Issue by alejandrogallo** [papis/papis-zotero#4]
Maybe someone can share some files for it.

**Comment by stasvlasov** [comment]
Here an example of zotero.sqlite. I made it with Zotero 5.0.60.

- Just zotero.sqlite - https://www.dropbox.com/s/u0u648oi7uvydpg/zotero.sqlite?dl=0
- Full folder with several pdfs (~45Mb unzipped) - https://www.dropbox.com/s/7xufvj5ftoiinev/zotero.zip?dl=0

Hope it will help testing!

**Comment by alejandrogallo** [comment]
Thanks @stasvlasov, I'll get to it :)

**Comment by alejandrogallo** [comment]
I just added some tests for the sql with your database, of course I modified the pdfs inside your folder
so that we don't get any trouble with copyright infringement, so the pdfs in the tests are mock pdfs.
Thanks so much for this!
