### ISSUE TITLE
Add a command line flag to automatically accept/reject duplicates

### ISSUE THREAD

**Issue by jfsantos** [papis/papis-zotero#7]
When importing from a large .bib file with multiple duplicates, `papis zotero import` shows a duplication warning for each file. It is very annoying to have to confirm each file, especially if you have a large database edited manually with lots of duplicates. Would it be possible to add flags `--accept-duplicates` and `--reject-duplicates` that would skip the interactive window and just accept/reject all duplicates?

**Comment by alejandrogallo** [comment]
I agree it's useful.

**Comment by alexfikl** [comment]
The importer now uses `papis add` underneath, so it should ask if duplicates are detected.
